whitelist_rules:
  - class_delegate_protocol
  - closing_brace
  - colon
  - comma
  - cyclomatic_complexity
  - empty_enum_arguments
  - file_length
  - force_cast
  - force_unwrapping
  - function_body_length
  - todo
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace
  - weak_delegate
included: # paths to include during linting. `--path` is ignored if present.
  - ProjectTemplate
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Source/Generated
  - Carthage
  - Pods
force_cast: warning # implicitly
function_body_length:
  - 100 # warning
  - 300 # error
type_body_length:
  - 300 # warning
  - 500 # error
file_length:
  warning: 500
  error: 1200
# reporter: "csv" # reporter type (xcode, json, csv, checkstyle)
