import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: projectName,
    projects: ["."],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .enabled(
        codeCoverageMode: .targets(projectTargets.map { .init(projectPath: nil, target: $0.name) }),
        testLanguage: "cs",
        testRegion: "CZ"
    ))
)
