#!/bin/sh

CURRENT_ENV_FILE="${ACK_ENVIRONMENT_DIR}/.current"
ENVIRONMENT=`cat ${CURRENT_ENV_FILE} || echo "Development"`
SELECTED_ENV_DIR="${ACK_ENVIRONMENT_DIR}/${ENVIRONMENT}"
CURRENT_ENV_DIR="${ACK_ENVIRONMENT_DIR}/Current"

rm -rf "${CURRENT_ENV_DIR}"
cp -r "${SELECTED_ENV_DIR}" "${CURRENT_ENV_DIR}"
touch "${INFOPLIST_FILE}"
touch "$CURRENT_ENV_DIR"
