name: Build

on: [pull_request, push]

jobs:
  spm:
    name: SPM tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run tests
        run: swift test
  carthage:
    name: Carthage build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3.3.1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Fetch Carthage dependencies
        run: carthage checkout
      - name: Carthage build
        run: carthage build --no-skip-current --cache-builds --use-xcframeworks
  tests:
    name: Build
    runs-on: macos-13
    defaults:
      run:
        working-directory: ./ProjectTemplate
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3.3.1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Install Tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Build Carthage dependencies
        run: carthage bootstrap --platform iOS --cache-builds --use-xcframeworks
      - name: Generate project
        run: tuist fetch && tuist generate
      - name: Build project
        run: set -o pipefail && xcodebuild -scheme App -workspace ProjectTemplate.xcworkspace -sdk iphonesimulator ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO | xcpretty
