name: Build

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Build Carthage dependencies
        run: carthage bootstrap --cache-builds --use-xcframeworks
      - name: Build project
        run: |
          bash <(curl -Ls https://install.tuist.io)
          tuist fetch
          tuist generate
          tuist build
