name: Build

on: [pull_request, push]

jobs:
  carthage:
    name: Carthage build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Fetch Carthage dependencies
        run: carthage checkout
      - name: Carthage build
        run: carthage build --no-skip-current --cache-builds --use-xcframeworks
  tests:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3
        with:
          path: ../Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Install Tuist
        run:  |
          curl https://mise.run | sh
          eval "$(~/.local/bin/mise activate bash)"
          mise install tuist
      - name: Build Carthage dependencies
        run: carthage bootstrap --cache-builds --use-xcframeworks
      - name: Generate project
        run: tuist fetch && tuist generate
      - name: Build project
        run: tuist build
