name: Build

on: [pull_request, push]

jobs:
  tests:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install gems
        run: bundle install
      - name: Install Tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - uses: olejnjak/carthage-workaround@main
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          action: bootstrap --platform iOS --cache-builds
      - name: Generate project
        run: tuist up; tuist generate
      - name: Build project
        run: set -o pipefail && xcodebuild -scheme Development -workspace ProjectTemplate.xcworkspace -sdk iphonesimulator  ONLY_ACTIVE_ARCH=YES | xcpretty