name: Build

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Install Tuist
        run:  |
          curl https://mise.run | sh
          ~/.local/bin/mise install tuist
      - name: Build Carthage dependencies
        run: carthage bootstrap --cache-builds --use-xcframeworks
      - name: Generate project
        run: |
          ~/.local/bin/mise exec -- tuist fetch
          ~/.local/bin/mise exec -- tuist generate
      - name: Build project
        run: ~/.local/bin/mise exec -- tuist build
