# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idname
name: Checks

on: [pull_request]

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.3.0
        with:
          changelog_regex: 'CHANGELOG.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}